ENSApp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

from .views import (
    LogIn,
    success,
    user_logout,
    SignUp,
    profile,
    create_profile,
    edit_profile
)

urlpatterns = [
    path("", LogIn.as_view(), name="login"),
    path("success/", success, name="success"),
    path("logout/", user_logout, name="logout"),
    path("signup/", SignUp.as_view(), name="signup"),
    #for crud profile
    path('profile/', profile, name='profile'),
    path('create_profile/', create_profile, name='create_profile'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    #for crud tr_expenses
    path('punch_in/', views.punch_in, name='punch_in'),
    path('punchindetails',views.show_punchin, name='punchindetails'),
    #for Punch Out
    path('punch_out/', views.punch_out_create,name='punch_out'),
    path('punchoutdetails',views.punch_out_details, name='punchoutdetails'),
    path('cost',views.total_expense,name='total_cost'),
    path('allin',views.all_punchin,name='allpunchin'),
    path('allout',views.all_punchout,name='allpunchout'),
    path('attendance',views.attendance,name='attendance'),
    path('pdf',views.download_pdf,name='pdf'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ENSPL/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header="Ellora Natural Seeds Pvt Ltd"
admin.site.site_title="Ellora Natural Seeds Pvt Ltd"
admin.site.index_title="Welcome to Admin Panel"

from rest_framework import routers
from ENSApp.views import EmployeeProfileViewSet, PunchInViewSet, PunchOutViewSet, TotalExpenseViewSet, DailyAttendanceViewSet, UserViewSet

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'employee-profiles', EmployeeProfileViewSet)
router.register(r'punch-in', PunchInViewSet)
router.register(r'punch-out', PunchOutViewSet)
router.register(r'total-expense', TotalExpenseViewSet)
router.register(r'daily-attendance', DailyAttendanceViewSet)

urlpatterns = [ 
    path("admin/", admin.site.urls),
    path("", include('ENSApp.urls')),
    path('api/', include(router.urls)),
   
] 
if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ENSApp/models.py
from django.db import models
from django.contrib.auth.models import User



class EmployeeProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='images/', default='default.png')
    department = models.CharField(max_length=100)
    designation = models.CharField(max_length=100)
    vehicle_number=models.CharField(max_length=10)
    phone_number = models.CharField(max_length=20)
    birth_date = models.DateField(null=True, blank=True)
    address = models.CharField(max_length=200)
    work_location = models.CharField(max_length=30, blank=True)
    

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name} ({self.department})"

#Punch In

class Punch_In(models.Model):
    VEHICLE_CHOICES = [
        ('2 wheeler', 'Two Wheeler'),
        ('4 wheeler', 'Four Wheeler'),
        ('By Train', 'By Train'),
        ('By Bus','By Bus'),
        ('By Auto','By Auto')
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True,null=True)
    time=models.TimeField(auto_now_add=True, null=True)
    vehicle_type = models.CharField(max_length=9, choices=VEHICLE_CHOICES)
    from_location = models.CharField(max_length=100)
    to_location = models.CharField(max_length=100)
    meter_photo = models.ImageField(upload_to='meter_photos/',verbose_name = "Meter Photo",null=True)
    manual_reading = models.IntegerField(verbose_name = "Manual Reading",default=0,null=True)
    ticket_amount = models.IntegerField(null=True)
    ticket_photo = models.ImageField(upload_to='meter_photos/',null=True)
    todays_work = models.TextField()

    def __str__(self):
        return f'{self.date} - {self.user.username} - {self.user.first_name} {self.user.last_name}'

    class Meta:
         verbose_name_plural = "Punch In"


#Punch Out
class Punch_Out(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True,null=True)
    time=models.TimeField(auto_now_add=True, null=True)
    from_location = models.CharField(max_length=100)
    to_location = models.CharField(max_length=100)
    meter_photo = models.ImageField(upload_to='meter_photos/',verbose_name = "Meter Photo")
    manual_reading = models.IntegerField(verbose_name = "Manual Reading",default=0, null=True)
    ticket_amount = models.IntegerField(default=0,null=True)
    ticket_photo = models.ImageField(upload_to='meter_photos/',null=True)
    daily_allounce = models.IntegerField(default=0,verbose_name = "DA",null=True)
    lodging = models.IntegerField(default=0,verbose_name = "Lodging/Boarding",null=True)
    lodging_photo = models.ImageField(upload_to='meter_photos/',null=True,blank=True)
    todays_work = models.TextField()

    def __str__(self):
        return f'{self.date} - {self.user.username} - {self.user.first_name} {self.user.last_name}'

    class Meta:
         verbose_name_plural = "Punch Out"

class Total_Expense(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    vehicle_type=models.CharField(max_length=10)
    date = models.DateField(auto_now_add=True)
    punchin_from=models.CharField(max_length=200)
    punchin_to=models.CharField(max_length=200)
    punchout_from=models.CharField(max_length=200)
    punchout_to=models.CharField(max_length=200)
    morning_reading = models.IntegerField(default=0,verbose_name = "Manual Reading")
    evening_reading = models.IntegerField(default=0,verbose_name = "Manual Reading")
    ticket = models.IntegerField(default=0)
    d_a = models.IntegerField(default=0,verbose_name = "DA")
    lodging_boarding = models.IntegerField(default=0,verbose_name = "Lodging/Boarding")
    daily_km = models.IntegerField(default=0)
    daily_cost = models.FloatField(default=0)

    def __str__(self):
        return f"{self.date} - {self.user.username}  - {self.daily_cost}"
    class Meta:
     verbose_name_plural = "Total Expense"


class Daily_Attendance(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    intime=models.TimeField(null=True)
    outtime=models.TimeField(null=True)
    date = models.DateField(auto_now_add=True)
    present = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.date} - {self.user.username} - {self.user.first_name} {self.user.last_name} - {self.present} '

    class Meta:
         verbose_name_plural = "Daily Attendance"

ENSApp/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.http import HttpResponse
from datetime import date

class LogIn(LoginView):
    template_name = 'login.html'

    def post(self, request, *args, **kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')
        rememberme = request.POST.get('rememberme')

        user_obj = User.objects.filter(username=username).first()
        if user_obj is None:
            messages.success(request=request, message="User not found!!!")
            return redirect('login')
        user = authenticate(username=username, password=password)
        if user is None:
            messages.success(request=request, message="Incorrect password")
            return redirect('login')
        login(request=request, user=user)
        if not rememberme:
            self.request.session.set_expiry(0)
            self.request.session.modified = True
        return redirect('profile')


class SignUp(CreateView):
    model = User
    fields = "__all__"
    template_name = 'register.html'
    success_url = reverse_lazy('login')

    def post(self, request, *args, **kwargs):
        try:
            password1 = request.POST.get('password1')
            password2 = request.POST.get('password2')
            username = request.POST.get('username')
            email = request.POST.get('email')
            first_name = request.POST.get('firstname')
            last_name = request.POST.get('lastname')

            if password1 != password2:
                messages.success(request, 'The passwords in both password fields are not the same!!!')
                return redirect('signup')

            if User.objects.filter(username=username).first():
                messages.success(request, "Such a user has already registered!!!")
                return redirect('signup')

            if User.objects.filter(email=email).first():
                messages.success(request, "This Employee has already been registered!!!")
                return redirect('signup')

            user_obj = User.objects.create(username=username, email=email, first_name=first_name, last_name=last_name)
            user_obj.set_password(raw_password=password1)
            user_obj.save()
            return redirect('profile')
        except Exception as e:
            messages.error(request, f"Error {e}")
            return redirect('signup')


def success(request):
    return render(request=request, template_name='success.html', context={})


def user_logout(request):
    logout(request)
    return redirect(to='login')


#For profile..
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import EmployeeProfile
from .forms import EmployeeProfileForm


@login_required
def profile(request):
    try:
        user = request.user
        user_profile = EmployeeProfile.objects.get(user=user)
    except EmployeeProfile.DoesNotExist:
        return render(request, 'base.html')
    return render(request, 'profile.html', {'user': user, 'user_profile': user_profile})

@login_required
def create_profile(request):
    if request.method == 'POST':
        form = EmployeeProfileForm(request.POST, request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            messages.success(request, 'Profile created successfully.')
            return redirect('profile')
    else:
        form = EmployeeProfileForm()
    return render(request, 'create_profile.html', {'form': form})

@login_required
def edit_profile(request):
    user_profile = get_object_or_404(EmployeeProfile, user=request.user)
    if request.method == 'POST':
        form = EmployeeProfileForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = EmployeeProfileForm(instance=user_profile)
    return render(request, 'edit_profile.html', {'form': form})


#Punch In

from .forms import PunchInForm
from .models import Punch_In
from .models import Daily_Attendance
from .models import Total_Expense

@login_required
def punch_in(request):
    user = request.user
    if request.method == 'POST':
        form = PunchInForm(request.POST, request.FILES)
        last_punchin = Punch_In.objects.last()
        if form.is_valid():
            attendance = form.save(commit=False)
            attendance.user = request.user
            attendance.save()
            # Update the attendance record in the attendance table
            attendance_record, created = Daily_Attendance.objects.get_or_create(
                user=request.user,
                date=attendance.date,
                intime=attendance.time
            )
            attendance_record.present = "Present"
            attendance_record.save()
            messages.success(request, 'Punch In saved successfully.')
            return redirect('punch_in')
            
    else:
        form = PunchInForm()
    return render(request, 'punch_in.html', {'form': form})

@login_required
def show_punchin(request):
    user = request.user
    today=date.today()
    try:
        punchin = Punch_In.objects.filter(user=user).order_by('-date', '-time').first()
        return render(request, 'punch_in_details.html', {'punchin': punchin})
    except Punch_In.DoesNotExist:
        return HttpResponse("No record found")
    except Punch_In.MultipleObjectsReturned:
        return HttpResponse("Multiple records found")


#Punch In
from django.shortcuts import render, redirect
from .models import Punch_Out, Total_Expense
from .forms import PunchOutForm
from django.db import IntegrityError
@login_required
def punch_out_create(request):
    if request.method == 'POST':
        form = PunchOutForm(request.POST, request.FILES)
        if form.is_valid():
            punch_out = form.save(commit=False)
            punch_out.user = request.user
            punch_out.save()
            attendance_records = Daily_Attendance.objects.filter(user=request.user, date=date.today())
            
            if attendance_records.exists():
                attendance_record = attendance_records.first()  # Select the first matching object
                attendance_record.outtime = punch_out.time
                attendance_record.save()
            
            messages.success(request, 'Punch Out saved successfully.')
            last_punchout = Punch_Out.objects.last()
            last_punchin = Punch_In.objects.last()
            vehicle=Punch_In.objects.last()

            if last_punchin.vehicle_type == '4 wheeler':
                daily_km = last_punchout.manual_reading - last_punchin.manual_reading
                daily_cost = daily_km * 10 + (last_punchout.daily_allounce ) + (last_punchout.lodging )
            elif last_punchin.vehicle_type == '2 wheeler':
                daily_km = last_punchout.manual_reading - last_punchin.manual_reading
                daily_cost = (daily_km * 3.5) + int(last_punchout.daily_allounce or 0) + int(last_punchout.lodging or 0 )

            elif last_punchin.vehicle_type == 'By Train':
                daily_km = 0
                daily_cost = (last_punchout.ticket_amount or 0 )+ (last_punchout.daily_allounce or 0) +(last_punchout.lodging or 0)+(last_punchin.ticket_amount or 0)

            elif last_punchin.vehicle_type == 'By Bus':
                daily_km = 0
                daily_cost = (last_punchout.ticket_amount or 0)+ (last_punchout.daily_allounce or 0) +(last_punchout.lodging or 0)+(last_punchin.ticket_amount or 0)

            elif last_punchin.vehicle_type == 'By Auto':
                daily_km = 0
                daily_cost = (last_punchout.ticket_amount or 0)+ (last_punchout.daily_allounce or 0) +(last_punchout.lodging or 0)+(last_punchin.ticket_amount or 0)


            else:
                daily_cost = 0

            try:
                total_expense = Total_Expense.objects.create(
    user=request.user,
    daily_km=daily_km or 0,
    daily_cost=daily_cost or 0,
    vehicle_type=vehicle.vehicle_type,
    punchin_from=last_punchin.from_location,
    punchin_to=last_punchin.to_location,
    punchout_from=last_punchout.from_location,
    punchout_to=last_punchout.to_location,
    morning_reading=last_punchin.manual_reading or 0,
    evening_reading=last_punchout.manual_reading or 0,
    ticket=(last_punchout.ticket_amount or 0) + (last_punchin.ticket_amount or 0),
    d_a=last_punchout.daily_allounce or 0,
    lodging_boarding=last_punchout.lodging or 0
)

                total_expense.save()
            except IntegrityError:
                total_expense = Total_Expense.objects.get(user=request.user, date=date.today())
                total_expense.save()
        return redirect('punch_out')
    else:
            form = PunchOutForm()
    
    return render(request, 'punch_out_create.html', {'form': form})

@login_required
def all_punchin(request):
    user = request.user
    punch_in=Punch_In.objects.filter(user=user)
    return render(request, 'all_punchins.html',{'punch_in': punch_in})

@login_required
def punch_out_details(request):
    user = request.user
    punch_out = Punch_Out.objects.filter(user=user).order_by('-date', '-time').first()
    return render(request, 'punch_out_details.html', {'punch_out': punch_out})

@login_required
def all_punchout(request):
    user = request.user
    punch_out=Punch_Out.objects.filter(user=user)
    return render(request, 'all_punchouts.html',{'punch_out': punch_out})

from django.core.paginator import Paginator
from django.db.models import Sum

ENSApp/templates/base.html
{% load static %}
<!doctype html>
<html lang="Eng">
  <head>
<style>
.container {
  display: flex;
  align-items: center;
  justify-content: flex-start
}

img {
  max-width: 80%;
  max-height:50%;
}

.text {
  font-size: 15px;
  padding-left: 5px;
}
  </style>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.rtl.min.css" integrity="sha384-WJUUqfoMmnfkBLne5uxXj+na/c7sesSJ32gI7GfCk4zO4GthUKhSEGyvQ839BC51" crossorigin="anonymous">

    <title>Ellora Natural Seeds Pvt Ltd</title>
    <link rel="icon" type="image/png" href="media/logo.png">

  </head>
  <body>
    <h1 style = "color:green;"> Ellora Natural Seeds Pvt Ltd.</h1>

    <!-- Optional JavaScript; choose one of the two! -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <H4><a class="navbar-brand" href="#">Home</a></H4>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link" href="{% url 'punch_in' %}">Punch In</a>
            <a class="nav-link" href="{% url 'punch_out' %}">Punch Out</a>
            <a class="nav-link" href="{% url 'attendance' %}">Attendance</a>
            <a class="nav-link" href="{% url 'total_cost' %}">Expenses</a>
            <a class="nav-link" href="{% url 'logout' %}">LogOut</a>
          </div>
        </div>
      </div>
    </nav>
  <h3>Profile Not Available</h3>
  <p>
  <a href="{% url 'create_profile' %}">Create Profile</a>
  </p>
</form>
</div>
</div>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    -->
  </body>
</html>

{% extends "admin/base.html" %}

{% block branding %}
    <h1 id="site-name"><a href="{% url 'admin:index' %}">My Custom Admin</a></h1>
    <div class="my-custom-logo">
        <img src="{% static 'images/default.png' %}" alt="Custom Logo">
    </div>
{% endblock %}

ENSApp/templates/expense_list.html
{% extends 'base.html' %}

{% block content %}
<title>Ellora Natural Seeds Pvt Ltd</title>
  <h1>Expense List</h1>
  <table>
    <thead>
      <tr>
        <th>Employee Name</th>
        <th>Date/Time</th>
        <th>Todays Work</th>
        <th>Source</th>
        <th>Destination</th>
        <th>Reading Image</th>
        <th>Manual Reading</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for expense in expenses %}
        <tr>
          <td>{{ expense.empname }}</td>
          <td>{{ expense.intime }}</td>
          <td>{{ expense.todays_work }}</td>
          <td>{{ expense.source }}</td>
          <td>{{ expense.destination }}</td>
          <td><img src="{{ expense.reading_image.url }}" height="50" /></td>
          <td>{{ expense.manual_reading }}</td>
          <td>
            <a href="{% url 'expense_update' expense.pk %}">Update</a>
            <a href="{% url 'expense_delete' expense.pk %}">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
 

ENSApp/templates/punch_in_details.html
{% load static %}
<!doctype html>
<html lang="Eng">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.rtl.min.css" integrity="sha384-WJUUqfoMmnfkBLne5uxXj+na/c7sesSJ32gI7GfCk4zO4GthUKhSEGyvQ839BC51" crossorigin="anonymous">

    <title>Ellora Natural Seeds Pvt Ltd</title>
    <link rel="icon" type="image/png" href="media/logo.png">

  </head>
  <body>
    <h1 style = "color:green;"> Ellora Natural Seeds Pvt Ltd.</h1>

    <!-- Optional JavaScript; choose one of the two! -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <H4><a class="navbar-brand" href="{% url 'profile' %}">Home</a></H4>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link" href="{% url 'punch_in' %}">Punch In</a>
            <a class="nav-link" href="{% url 'punch_out' %}">Punch Out</a>
            <a class="nav-link" href="{% url 'attendance' %}">Attendance</a>
            <a class="nav-link" href="{% url 'total_cost' %}">Expenses</a>
            <a class="nav-link" href="{% url 'logout' %}">LogOut</a>
          </div>
        </div>
      </div>
    </nav>
    {% if punchin.meter_photo and not punchin.meter_photo.is_empty %}
    <p>Employee Id: {{ user.username }}</p>
    <p>Date: {{ punchin.date }}</p>
    <p>Time: {{ punchin.time }}</p>
    <p>Vehicle type: {{ punchin.get_vehicle_type_display }}</p>
    <p>From location: {{ punchin.from_location }}</p>
    <p>To location: {{ punchin.to_location }}</p>
    <p>Manual Reading: {{ punchin.manual_reading }}</p>
    <p>Ticket Amount: {{ punchin.ticket_amount }}</p>
    <p>Ticket photo: No ticket photo available</p>
    <p>Today's work: {{ punchin.todays_work }}</p>
    <p>Meter photo: <img src="{{ punchin.meter_photo.url }}" alt="{{ punchin.meter_photo.name }}" width="250" height="250"></p>
    
    {% elif punchin in punchin %}
    <p>Employee Id: {{ user.username }}</p>
    <p>Date: {{ punchin.date }}</p>
    <p>Time: {{ punchin.time }}</p>
    <p>Vehicle type: {{ punchin.get_vehicle_type_display }}</p>
    <p>From location: {{ punchin.from_location }}</p>
    <p>To location: {{ punchin.to_location }}</p>
    <p>Manual Reading: {{ punchin.manual_reading }}</p>
    <p>Ticket Amount: {{ punchin.ticket_amount }}</p>
    <p>Ticket photo: <img src="{{ punchin.ticket_photo.url }}" alt="{{ punchin.ticket__photo.name }}" width="250" height="250"></p>
    <p>Today's work: {{ punchin.todays_work }}</p>
    <p>Meter photo: <img src="{{ punchin.meter_photo.url }}" alt="{{ punchin.meter_photo.name }}" width="250" height="250"></p>
   
    {% else %}
    <p>Employee Id: {{ user.username }}</p>
    <p>Date: {{ punchin.date }}</p>
    <p>Time: {{ punchin.time }}</p>
    <p>Vehicle type: {{ punchin.get_vehicle_type_display }}</p>
    <p>From location: {{ punchin.from_location }}</p>
    <p>To location: {{ punchin.to_location }}</p>
    <p>Manual Reading: {{ punchin.manual_reading }}</p>
    <p>Ticket Amount: {{ punchin.ticket_amount }}</p>
    <p>Ticket photo: <img src="{{ punchin.ticket_photo.url }}" alt="{{ punchin.ticket__photo.name }}" width="250" height="250"></p>
    <p>Today's work: {{ punchin.todays_work }}</p>
    <p>No meter photo available</p>
    {% endif %}
</form>
 
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    -->
  </body>
</html>

ENSApp/templates/punch_in_out_cost.html
    <h2>{{ punch_in }}</h2>
    <p>Manual reading difference: {{ punch_in.manual_reading_diff }}</p>
    <p>Cost: Rs. {{ punch_in.cost }}</p>

ENSApp/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ellora Natural Seeds Pvt Ltd</title>
</head>
<body>
{% if messages %}
    {% for message in messages %}
        {{ message }}
    {% endfor %}
{% endif %}<br>
<a href="{% url 'logout' %}">LogOut</a>
</body>
</html>